//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeltionHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Customer = new Customer();
        }
        public int OrderID { get; set; }
        public string roomNo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> price { get; set; }
        public string comment { get; set; }
        public Nullable<int> CusID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
